# Generated by Django 3.2.17 on 2023-02-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersignup',
            name='created_at',
        ),
    ]
