# Generated by Django 3.2.17 on 2023-02-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitestats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitestats',
            options={'verbose_name': 'Website Views', 'verbose_name_plural': 'Website Views'},
        ),
    ]
