# Generated by Django 3.2.17 on 2023-02-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitestats', '0002_alter_sitestats_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitestats',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sitestats',
            name='page',
        ),
        migrations.AddField(
            model_name='sitestats',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitestats',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
