# Generated by Django 3.2.17 on 2023-02-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitestats', '0003_auto_20230217_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitestats',
            options={},
        ),
    ]
