# Generated by Django 3.2.17 on 2023-02-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitestats', '0004_alter_sitestats_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitestats',
            options={'verbose_name': 'Homepage Views', 'verbose_name_plural': 'Homepage Views'},
        ),
        migrations.AlterField(
            model_name='sitestats',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='sitestats',
            unique_together={('url',)},
        ),
    ]
