# Generated by Django 3.2.17 on 2023-02-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'User Feedback', 'verbose_name_plural': 'User Feedback'},
        ),
    ]
